quarkus:
  log:
    category:
      "com.blocktrust":
        level: DEBUG
    console:
      enable: true
    file:
      enable: false

  live-reload:
    instrumentation: true

  datasource:
    jdbc:
      url: jdbc:h2:tcp://localhost/~/app-home/workbench-service/db/h2-dev;AUTO_SERVER=true;DB_CLOSE_DELAY=-1

#  keycloak:
#    devservices:
#      realm-path: keycloak.json
