
quarkus:
#  oidc:
#    auth-server-url: ${keycloak.url}/realms/quarkus/
#    client-id: quarkus-service-app
#    credentials: secret
#    application-type: service

#  keycloak:
#    devservices:
#      realm-path: quarkus-realm.json

  datasource:
    db-kind: h2
    username: sa
    password:
    jdbc:
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1

  hibernate-orm:
    database:
      generation: update